apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/sonatype/docker-nexus3
  labels:
    app: nexus3
    app.kubernetes.io/component: nexus3
    app.kubernetes.io/instance: nexus3
    app.kubernetes.io/part-of: nexus3-app
  name: nexus3
spec:
  lookupPolicy:
    local: false
