apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3.30.0
    app.openshift.io/vcs-uri: https://github.com/sonatype/docker-nexus3
  labels:
    app: nexus3
    app.kubernetes.io/component: nexus3
    app.kubernetes.io/instance: nexus3
    app.kubernetes.io/part-of: nexus3-app
  name: nexus3
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nexus3:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: 3.30.0
      uri: https://github.com/sonatype/docker-nexus3
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.rh.ubi
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
